## Preprocessing

In [35]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [7]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [8]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
#  YOUR CODE GOES HERE
application_df = application_df.drop(columns=["EIN", "NAME"])

In [9]:
# Determine the number of unique values in each column.
#  YOUR CODE GOES HERE
for column in application_df.columns:
    unique_values = application_df[column].nunique()
    print(f"Unique values for {column}: {unique_values}")

Unique values for APPLICATION_TYPE: 17
Unique values for AFFILIATION: 6
Unique values for CLASSIFICATION: 71
Unique values for USE_CASE: 5
Unique values for ORGANIZATION: 4
Unique values for STATUS: 2
Unique values for INCOME_AMT: 9
Unique values for SPECIAL_CONSIDERATIONS: 2
Unique values for ASK_AMT: 8747
Unique values for IS_SUCCESSFUL: 2

In [10]:
# Look at APPLICATION_TYPE value counts for binning
#  YOUR CODE GOES HERE
print(application_df['APPLICATION_TYPE'].value_counts())

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [14]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE
cutoff_value = 1000  

application_types_to_replace = application_df['APPLICATION_TYPE'].value_counts()[application_df['APPLICATION_TYPE'].value_counts() < cutoff_value].index.tolist()

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
Other     2266
T4        1542
T6        1216
T5        1173
T19       1065
Name: APPLICATION_TYPE, dtype: int64

In [16]:
# Look at CLASSIFICATION value counts for binning
#  YOUR CODE GOES HERE
print(application_df['CLASSIFICATION'].value_counts())

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: CLASSIFICATION, dtype: int64

In [18]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#  YOUR CODE GOES HERE
c_c = application_df['CLASSIFICATION'].value_counts()
c_c1 = c_c[c_c > 1]
print(c_c1)

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: CLASSIFICATION, dtype: int64

In [20]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE
cutoff_value = 1000  
classifications_to_replace = application_df['CLASSIFICATION'].value_counts()[application_df['CLASSIFICATION'].value_counts() < cutoff_value].index.tolist()
# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [30]:
# Convert categorical data to numeric with `pd.get_dummies`
#  YOUR CODE GOES HERE
categorical_columns = ['APPLICATION_TYPE', 'AFFILIATION', 'ASK_AMT', 'CLASSIFICATION', 'USE_CASE', 'ORGANIZATION', 'INCOME_AMT', 'SPECIAL_CONSIDERATIONS']
application_df_en = pd.get_dummies(application_df[categorical_columns])

In [31]:
df_processed = pd.concat([application_df, application_df_en], axis=1)

# Drop the original categorical columns
df_processed.drop(categorical_columns, axis=1, inplace=True)

In [32]:
df_processed.head(20)

,STATUS,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,AFFILIATION_CompanySponsored,AFFILIATION_Family/Parent,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,1,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,0,0,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,1,0,0,1,0,0,0,1,0,...,0,1,0,0,0,0,0,0,1,0
4,1,1,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
5,1,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
6,1,1,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
7,1,1,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
8,1,1,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
9,1,0,0,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,1,0
10,1,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
11,1,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
12,1,1,0,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
13,1,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
14,1,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
15,1,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
16,1,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
17,1,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
18,1,0,0,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
19,1,0,0,0,1,0,0,0,1,0,...,0,0,1,0,0,0,0,0,1,0

In [37]:
df_processed.shape

(34299, 42)

In [33]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE
target = df_processed["IS_SUCCESSFUL"]
features = df_processed.drop(columns=["IS_SUCCESSFUL"])
X = features.values
y = target.values

# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

In [34]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [43]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE

nn = tf.keras.models.Sequential()

# First hidden layer
#  YOUR CODE GOES HERE
# First hidden layer
number_input_features = 41
hidden_layer1_units = 80
hidden_layer2_units = 30
nn.add(tf.keras.layers.Dense(units=hidden_layer1_units, input_dim=number_input_features, activation='relu'))
# Second hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=hidden_layer2_units, activation='relu'))
# Output layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
# Check the structure of the model
nn.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_9 (Dense)             (None, 80)                3360

 dense_10 (Dense)            (None, 30)                2430

 dense_11 (Dense)            (None, 1)                 31

=================================================================
Total params: 5821 (22.74 KB)
Trainable params: 5821 (22.74 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [44]:
# Compile the model
#  YOUR CODE GOES HERE
nn.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

In [45]:
# Train the model
#  YOUR CODE GOES HERE
callback = tf.keras.callbacks.ModelCheckpoint(filepath="AlphabetSoupCharity.h5", save_weights_only=True, save_freq="epoch", period=5)
nn.fit(X_train_scaled, y_train, epochs=100, callbacks=[callback], validation_data=(X_test_scaled, y_test))

WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.
Epoch 1/100
804/804 [==============================] - 1s 603us/step - loss: 0.5748 - accuracy: 0.7200 - val_loss: 0.5657 - val_accuracy: 0.7184
Epoch 2/100
804/804 [==============================] - 0s 464us/step - loss: 0.5573 - accuracy: 0.7307 - val_loss: 0.5624 - val_accuracy: 0.7213
Epoch 3/100
804/804 [==============================] - 0s 470us/step - loss: 0.5546 - accuracy: 0.7318 - val_loss: 0.5606 - val_accuracy: 0.7209
Epoch 4/100
804/804 [==============================] - 0s 493us/step - loss: 0.5530 - accuracy: 0.7319 - val_loss: 0.5619 - val_accuracy: 0.7212
Epoch 5/100
804/804 [==============================] - 0s 475us/step - loss: 0.5511 - accuracy: 0.7339 - val_loss: 0.5615 - val_accuracy: 0.7213
Epoch 6/100
804/804 [==============================] - 0s 479us/step - loss: 0.5502 - accuracy: 0.7324 - val_loss: 0.5595 - val_accuracy: 0.7224
Epoch 7/100
804/804 [==============================] - 0s 465us/step - loss: 0.5495 - accuracy: 0.7347 - val_loss: 0.5616 - val_accuracy: 0.7250
Epoch 8/100
804/804 [==============================] - 0s 471us/step - loss: 0.5491 - accuracy: 0.7325 - val_loss: 0.5599 - val_accuracy: 0.7230
Epoch 9/100
804/804 [==============================] - 0s 521us/step - loss: 0.5485 - accuracy: 0.7353 - val_loss: 0.5609 - val_accuracy: 0.7188
Epoch 10/100
804/804 [==============================] - 0s 491us/step - loss: 0.5477 - accuracy: 0.7348 - val_loss: 0.5584 - val_accuracy: 0.7200
Epoch 11/100
804/804 [==============================] - 0s 469us/step - loss: 0.5469 - accuracy: 0.7350 - val_loss: 0.5599 - val_accuracy: 0.7245
Epoch 12/100
804/804 [==============================] - 0s 465us/step - loss: 0.5471 - accuracy: 0.7361 - val_loss: 0.5557 - val_accuracy: 0.7262
Epoch 13/100
804/804 [==============================] - 0s 465us/step - loss: 0.5468 - accuracy: 0.7354 - val_loss: 0.5565 - val_accuracy: 0.7240
Epoch 14/100
804/804 [==============================] - 0s 479us/step - loss: 0.5465 - accuracy: 0.7352 - val_loss: 0.5576 - val_accuracy: 0.7240
Epoch 15/100
804/804 [==============================] - 0s 472us/step - loss: 0.5463 - accuracy: 0.7360 - val_loss: 0.5602 - val_accuracy: 0.7229
Epoch 16/100
804/804 [==============================] - 0s 465us/step - loss: 0.5448 - accuracy: 0.7365 - val_loss: 0.5571 - val_accuracy: 0.7242
Epoch 17/100
804/804 [==============================] - 0s 468us/step - loss: 0.5451 - accuracy: 0.7359 - val_loss: 0.5575 - val_accuracy: 0.7198
Epoch 18/100
804/804 [==============================] - 0s 462us/step - loss: 0.5446 - accuracy: 0.7364 - val_loss: 0.5586 - val_accuracy: 0.7236
Epoch 19/100
804/804 [==============================] - 0s 564us/step - loss: 0.5444 - accuracy: 0.7366 - val_loss: 0.5596 - val_accuracy: 0.7229
Epoch 20/100
804/804 [==============================] - 0s 482us/step - loss: 0.5443 - accuracy: 0.7374 - val_loss: 0.5578 - val_accuracy: 0.7254
Epoch 21/100
804/804 [==============================] - 0s 468us/step - loss: 0.5437 - accuracy: 0.7367 - val_loss: 0.5591 - val_accuracy: 0.7250
Epoch 22/100
804/804 [==============================] - 0s 468us/step - loss: 0.5438 - accuracy: 0.7373 - val_loss: 0.5590 - val_accuracy: 0.7217
Epoch 23/100
804/804 [==============================] - 0s 477us/step - loss: 0.5436 - accuracy: 0.7374 - val_loss: 0.5591 - val_accuracy: 0.7215
Epoch 24/100
804/804 [==============================] - 0s 480us/step - loss: 0.5433 - accuracy: 0.7372 - val_loss: 0.5586 - val_accuracy: 0.7237
Epoch 25/100
804/804 [==============================] - 0s 474us/step - loss: 0.5434 - accuracy: 0.7377 - val_loss: 0.5590 - val_accuracy: 0.7229
Epoch 26/100
804/804 [==============================] - 0s 470us/step - loss: 0.5423 - accuracy: 0.7379 - val_loss: 0.5589 - val_accuracy: 0.7242
Epoch 27/100
804/804 [==============================] - 0s 489us/step - loss: 0.5425 - accuracy: 0.7386 - val_loss: 0.5586 - val_accuracy: 0.7227
Epoch 28/100
804/804 [==============================] - 0s 526us/step - loss: 0.5426 - accuracy: 0.7383 - val_loss: 0.5602 - val_accuracy: 0.7233
Epoch 29/100
804/804 [==============================] - 0s 468us/step - loss: 0.5424 - accuracy: 0.7389 - val_loss: 0.5576 - val_accuracy: 0.7251
Epoch 30/100
804/804 [==============================] - 0s 496us/step - loss: 0.5421 - accuracy: 0.7372 - val_loss: 0.5592 - val_accuracy: 0.7276
Epoch 31/100
804/804 [==============================] - 0s 472us/step - loss: 0.5417 - accuracy: 0.7383 - val_loss: 0.5593 - val_accuracy: 0.7200
Epoch 32/100
804/804 [==============================] - 0s 487us/step - loss: 0.5411 - accuracy: 0.7395 - val_loss: 0.5613 - val_accuracy: 0.7235
Epoch 33/100
804/804 [==============================] - 0s 477us/step - loss: 0.5412 - accuracy: 0.7386 - val_loss: 0.5617 - val_accuracy: 0.7202
Epoch 34/100
804/804 [==============================] - 0s 468us/step - loss: 0.5413 - accuracy: 0.7388 - val_loss: 0.5593 - val_accuracy: 0.7231
Epoch 35/100
804/804 [==============================] - 0s 477us/step - loss: 0.5411 - accuracy: 0.7388 - val_loss: 0.5599 - val_accuracy: 0.7243
Epoch 36/100
804/804 [==============================] - 0s 473us/step - loss: 0.5407 - accuracy: 0.7388 - val_loss: 0.5585 - val_accuracy: 0.7241
Epoch 37/100
804/804 [==============================] - 0s 477us/step - loss: 0.5408 - accuracy: 0.7394 - val_loss: 0.5599 - val_accuracy: 0.7226
Epoch 38/100
804/804 [==============================] - 0s 540us/step - loss: 0.5405 - accuracy: 0.7388 - val_loss: 0.5616 - val_accuracy: 0.7256
Epoch 39/100
804/804 [==============================] - 0s 486us/step - loss: 0.5405 - accuracy: 0.7388 - val_loss: 0.5607 - val_accuracy: 0.7252
Epoch 40/100
804/804 [==============================] - 0s 477us/step - loss: 0.5407 - accuracy: 0.7386 - val_loss: 0.5592 - val_accuracy: 0.7244
Epoch 41/100
804/804 [==============================] - 0s 483us/step - loss: 0.5402 - accuracy: 0.7389 - val_loss: 0.5593 - val_accuracy: 0.7254
Epoch 42/100
804/804 [==============================] - 0s 479us/step - loss: 0.5398 - accuracy: 0.7392 - val_loss: 0.5613 - val_accuracy: 0.7243
Epoch 43/100
804/804 [==============================] - 0s 475us/step - loss: 0.5403 - accuracy: 0.7384 - val_loss: 0.5601 - val_accuracy: 0.7220
Epoch 44/100
804/804 [==============================] - 0s 487us/step - loss: 0.5397 - accuracy: 0.7389 - val_loss: 0.5623 - val_accuracy: 0.7214
Epoch 45/100
804/804 [==============================] - 0s 474us/step - loss: 0.5402 - accuracy: 0.7388 - val_loss: 0.5614 - val_accuracy: 0.7261
Epoch 46/100
804/804 [==============================] - 0s 495us/step - loss: 0.5398 - accuracy: 0.7402 - val_loss: 0.5631 - val_accuracy: 0.7231
Epoch 47/100
804/804 [==============================] - 0s 545us/step - loss: 0.5400 - accuracy: 0.7392 - val_loss: 0.5608 - val_accuracy: 0.7243
Epoch 48/100
804/804 [==============================] - 0s 473us/step - loss: 0.5396 - accuracy: 0.7393 - val_loss: 0.5614 - val_accuracy: 0.7215
Epoch 49/100
804/804 [==============================] - 0s 470us/step - loss: 0.5393 - accuracy: 0.7400 - val_loss: 0.5605 - val_accuracy: 0.7262
Epoch 50/100
804/804 [==============================] - 0s 474us/step - loss: 0.5391 - accuracy: 0.7397 - val_loss: 0.5626 - val_accuracy: 0.7233
Epoch 51/100
804/804 [==============================] - 0s 472us/step - loss: 0.5393 - accuracy: 0.7403 - val_loss: 0.5612 - val_accuracy: 0.7210
Epoch 52/100
804/804 [==============================] - 0s 479us/step - loss: 0.5391 - accuracy: 0.7385 - val_loss: 0.5618 - val_accuracy: 0.7265
Epoch 53/100
804/804 [==============================] - 0s 496us/step - loss: 0.5392 - accuracy: 0.7390 - val_loss: 0.5600 - val_accuracy: 0.7215
Epoch 54/100
804/804 [==============================] - 0s 487us/step - loss: 0.5392 - accuracy: 0.7393 - val_loss: 0.5610 - val_accuracy: 0.7240
Epoch 55/100
804/804 [==============================] - 0s 476us/step - loss: 0.5386 - accuracy: 0.7399 - val_loss: 0.5678 - val_accuracy: 0.7216
Epoch 56/100
804/804 [==============================] - 0s 470us/step - loss: 0.5391 - accuracy: 0.7391 - val_loss: 0.5629 - val_accuracy: 0.7238
Epoch 57/100
804/804 [==============================] - 0s 549us/step - loss: 0.5391 - accuracy: 0.7397 - val_loss: 0.5606 - val_accuracy: 0.7263
Epoch 58/100
804/804 [==============================] - 0s 483us/step - loss: 0.5384 - accuracy: 0.7397 - val_loss: 0.5622 - val_accuracy: 0.7223
Epoch 59/100
804/804 [==============================] - 0s 479us/step - loss: 0.5382 - accuracy: 0.7400 - val_loss: 0.5630 - val_accuracy: 0.7241
Epoch 60/100
804/804 [==============================] - 0s 506us/step - loss: 0.5377 - accuracy: 0.7408 - val_loss: 0.5616 - val_accuracy: 0.7270
Epoch 61/100
804/804 [==============================] - 0s 471us/step - loss: 0.5386 - accuracy: 0.7393 - val_loss: 0.5616 - val_accuracy: 0.7238
Epoch 62/100
804/804 [==============================] - 0s 471us/step - loss: 0.5381 - accuracy: 0.7397 - val_loss: 0.5618 - val_accuracy: 0.7231
Epoch 63/100
804/804 [==============================] - 0s 473us/step - loss: 0.5382 - accuracy: 0.7394 - val_loss: 0.5609 - val_accuracy: 0.7226
Epoch 64/100
804/804 [==============================] - 0s 477us/step - loss: 0.5378 - accuracy: 0.7413 - val_loss: 0.5613 - val_accuracy: 0.7231
Epoch 65/100
804/804 [==============================] - 0s 477us/step - loss: 0.5378 - accuracy: 0.7397 - val_loss: 0.5618 - val_accuracy: 0.7240
Epoch 66/100
804/804 [==============================] - 0s 558us/step - loss: 0.5381 - accuracy: 0.7402 - val_loss: 0.5615 - val_accuracy: 0.7238
Epoch 67/100
804/804 [==============================] - 0s 482us/step - loss: 0.5373 - accuracy: 0.7402 - val_loss: 0.5636 - val_accuracy: 0.7237
Epoch 68/100
804/804 [==============================] - 0s 485us/step - loss: 0.5378 - accuracy: 0.7406 - val_loss: 0.5614 - val_accuracy: 0.7235
Epoch 69/100
804/804 [==============================] - 0s 483us/step - loss: 0.5375 - accuracy: 0.7402 - val_loss: 0.5605 - val_accuracy: 0.7259
Epoch 70/100
804/804 [==============================] - 0s 476us/step - loss: 0.5376 - accuracy: 0.7404 - val_loss: 0.5629 - val_accuracy: 0.7223
Epoch 71/100
804/804 [==============================] - 0s 475us/step - loss: 0.5375 - accuracy: 0.7409 - val_loss: 0.5616 - val_accuracy: 0.7242
Epoch 72/100
804/804 [==============================] - 0s 491us/step - loss: 0.5373 - accuracy: 0.7404 - val_loss: 0.5596 - val_accuracy: 0.7249
Epoch 73/100
804/804 [==============================] - 0s 473us/step - loss: 0.5373 - accuracy: 0.7404 - val_loss: 0.5610 - val_accuracy: 0.7265
Epoch 74/100
804/804 [==============================] - 0s 472us/step - loss: 0.5374 - accuracy: 0.7396 - val_loss: 0.5623 - val_accuracy: 0.7242
Epoch 75/100
804/804 [==============================] - 0s 531us/step - loss: 0.5374 - accuracy: 0.7397 - val_loss: 0.5611 - val_accuracy: 0.7244
Epoch 76/100
804/804 [==============================] - 0s 475us/step - loss: 0.5370 - accuracy: 0.7402 - val_loss: 0.5626 - val_accuracy: 0.7236
Epoch 77/100
804/804 [==============================] - 0s 486us/step - loss: 0.5373 - accuracy: 0.7403 - val_loss: 0.5610 - val_accuracy: 0.7245
Epoch 78/100
804/804 [==============================] - 0s 478us/step - loss: 0.5370 - accuracy: 0.7409 - val_loss: 0.5612 - val_accuracy: 0.7257
Epoch 79/100
804/804 [==============================] - 0s 516us/step - loss: 0.5369 - accuracy: 0.7402 - val_loss: 0.5629 - val_accuracy: 0.7251
Epoch 80/100
804/804 [==============================] - 0s 479us/step - loss: 0.5372 - accuracy: 0.7406 - val_loss: 0.5638 - val_accuracy: 0.7248
Epoch 81/100
804/804 [==============================] - 0s 472us/step - loss: 0.5372 - accuracy: 0.7393 - val_loss: 0.5648 - val_accuracy: 0.7270
Epoch 82/100
804/804 [==============================] - 0s 478us/step - loss: 0.5367 - accuracy: 0.7411 - val_loss: 0.5609 - val_accuracy: 0.7258
Epoch 83/100
804/804 [==============================] - 0s 483us/step - loss: 0.5367 - accuracy: 0.7410 - val_loss: 0.5633 - val_accuracy: 0.7244
Epoch 84/100
804/804 [==============================] - 0s 524us/step - loss: 0.5367 - accuracy: 0.7406 - val_loss: 0.5616 - val_accuracy: 0.7243
Epoch 85/100
804/804 [==============================] - 0s 476us/step - loss: 0.5369 - accuracy: 0.7412 - val_loss: 0.5643 - val_accuracy: 0.7257
Epoch 86/100
804/804 [==============================] - 0s 471us/step - loss: 0.5366 - accuracy: 0.7407 - val_loss: 0.5640 - val_accuracy: 0.7236
Epoch 87/100
804/804 [==============================] - 0s 495us/step - loss: 0.5368 - accuracy: 0.7399 - val_loss: 0.5639 - val_accuracy: 0.7256
Epoch 88/100
804/804 [==============================] - 0s 470us/step - loss: 0.5364 - accuracy: 0.7404 - val_loss: 0.5650 - val_accuracy: 0.7241
Epoch 89/100
804/804 [==============================] - 0s 472us/step - loss: 0.5362 - accuracy: 0.7401 - val_loss: 0.5653 - val_accuracy: 0.7216
Epoch 90/100
804/804 [==============================] - 0s 474us/step - loss: 0.5361 - accuracy: 0.7409 - val_loss: 0.5643 - val_accuracy: 0.7273
Epoch 91/100
804/804 [==============================] - 0s 485us/step - loss: 0.5363 - accuracy: 0.7404 - val_loss: 0.5653 - val_accuracy: 0.7268
Epoch 92/100
804/804 [==============================] - 0s 538us/step - loss: 0.5367 - accuracy: 0.7401 - val_loss: 0.5652 - val_accuracy: 0.7237
Epoch 93/100
804/804 [==============================] - 0s 471us/step - loss: 0.5362 - accuracy: 0.7405 - val_loss: 0.5619 - val_accuracy: 0.7249
Epoch 94/100
804/804 [==============================] - 0s 492us/step - loss: 0.5358 - accuracy: 0.7409 - val_loss: 0.5655 - val_accuracy: 0.7237
Epoch 95/100
804/804 [==============================] - 0s 475us/step - loss: 0.5360 - accuracy: 0.7413 - val_loss: 0.5649 - val_accuracy: 0.7258
Epoch 96/100
804/804 [==============================] - 0s 469us/step - loss: 0.5362 - accuracy: 0.7403 - val_loss: 0.5650 - val_accuracy: 0.7237
Epoch 97/100
804/804 [==============================] - 0s 475us/step - loss: 0.5364 - accuracy: 0.7409 - val_loss: 0.5653 - val_accuracy: 0.7247
Epoch 98/100
804/804 [==============================] - 0s 472us/step - loss: 0.5360 - accuracy: 0.7409 - val_loss: 0.5648 - val_accuracy: 0.7228
Epoch 99/100
804/804 [==============================] - 0s 473us/step - loss: 0.5359 - accuracy: 0.7406 - val_loss: 0.5645 - val_accuracy: 0.7256
Epoch 100/100
804/804 [==============================] - 0s 508us/step - loss: 0.5360 - accuracy: 0.7411 - val_loss: 0.5645 - val_accuracy: 0.7244

In [47]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5645 - accuracy: 0.7244 - 73ms/epoch - 271us/step
Loss: 0.5644713640213013, Accuracy: 0.7244315147399902

In [78]:
# Export our model to HDF5 file
#  YOUR CODE GOES HERE
nn.save("AlphabetSoupCharity_Optimization.h5")

/Users/dariareichkina/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(